#!/usr/bin/env bash

if [ $(id -u) -ne 0 ]; then
  echo "ERROR! You must be root."
  exit 1
fi

IS_PI=$(grep Model /proc/cpuinfo | grep Raspberry)
if [ $? -ne 0 ]; then
  echo "This is not a Raspberry Pi. Quitting!"
  exit 1
fi

IS_UBUNTU=$(lsb_release -is)
if [ "${IS_UBUNTU}" != "Ubuntu" ]; then
  echo "This script is only intended to run on Ubuntu."
  exit 1
fi

DESKTOP_PACKAGES="ubuntu-mate-desktop"
HARDWARE_PACKAGES="pi-bluetooth"

apt install "${DESKTOP_PACKAGES}^"
apt install "${HARDWARE_PACKAGES}"

mv /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml.bak
cat <<'EOF' > /etc/netplan/10-networkmanager-all.yaml
network:
  version: 2
  renderer: NetworkManager
EOF
